#!/bin/bash

SOURCE_PACKAGE_NAME=hostmot2-firmware
BUILDER_NAME="Hostmot2 Buildbot"
BUILDER_EMAIL="hm2-buildbot@linuxcnc.org"


if [ ! -d debian -o ! -d scripts ]; then
    echo "this script must be run from the root of the source tree (the directory with debian and scripts in it)"
    exit 1
fi


source scripts/githelper.sh
githelper $1

GIT_VERSION=$(scripts/get-version-from-git $GIT_BRANCH)
if [ $? -ne 0 ]; then
    echo "error determining version!"
    exit 1
fi

DEB_VERSION=`git show HEAD:debian/changelog | head -1 | sed 's/.*(\(.*\)).*/\1/'`

NEW_DEB_VERSION=$(echo $GIT_VERSION | sed -r 's/-pre/~pre/; s/-/./g')
NEW_DEB_VERSION=${NEW_DEB_VERSION/v/}

if [ "$NEW_DEB_VERSION" = "$DEB_VERSION" ]; then
    echo "no changes since the version at the top of the debian/changelog file"
    echo "not modifying debian/changelog"
    exit 0
fi

set -e
(
echo "$SOURCE_PACKAGE_NAME ($NEW_DEB_VERSION) $(lsb_release -cs); urgency=low"
echo
git log --pretty=format:"  * %w(72,0,6)%s" $GIT_TAG..
echo
echo
echo " -- $BUILDER_NAME <$BUILDER_EMAIL>  $(date -R)"
echo
git show HEAD:debian/changelog
) > debian/changelog

dch -r --nomultimaint ""
